In [1]:
!pip install openvino
!pip install openvino-dev[tensorflow2]


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.7/38.7 MB 15.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 14.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 33.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.9/489.9 MB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 69.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 40.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 66.7 MB/s eta 0:00:00
  Attempting uninstall: fastjsonschema
    Found existing installation: fastjsonschema 2.19.1
    Uninstalling fastjsonschema-2.19.1:
      Successfully uninstalled fastjsonschema-2.19.1
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.15.0
    Uninstalling tensorflow-estimator-2.15.0:
      Successfully uninstalled tensorflow-estimator-2.15.0
  Attempting uninstall: networkx
    Fou

In [ ]:
import tensorflow as tf

# Function to load a SavedModel
def load_saved_model(model_dir):
    # Load the SavedModel
    loaded = tf.saved_model.load(model_dir)
    return loaded

# Path to your SavedModel directory
model = load_saved_model("/content/gdrive/MyDrive/saved_model")

print(model.signatures)  # Print available model signatures (if any)


_SignatureMap({'serving_default': <ConcreteFunction signature_wrapper(*, input) at 0x7D27C5049AB0>})


In [ ]:
import tensorflow as tf

# Load the SavedModel
model = tf.saved_model.load("/content/gdrive/MyDrive/saved_model")

# Get the serving_default function
infer = model.signatures['serving_default']

# Prepare a sample input tensor. Adjust the shape and data type according to your model's needs.
# Example for an input tensor of shape (1, 300, 300, 3) and type float32
input_tensor = tf.random.normal([1, 300, 300, 3])

# Run inference
output = infer(input=input_tensor)

# Output is typically a dictionary with output tensor names as keys and Tensor values
print(output)
print("Input details:")
for input_name, input_value in infer.structured_input_signature[1].items():
    print(f"Name: {input_name}, Shape: {input_value.shape}, Type: {input_value.dtype}")

print("\nOutput details:")
for output_name, output_value in infer.structured_outputs.items():
    print(f"Name: {output_name}, Shape: {output_value.shape}, Type: {output_value.dtype}")

# Let's assume you have the concrete function and want to save it as a frozen graph
from tensorflow.python.framework import convert_to_constants

# Convert the concrete function to a fully frozen graph
frozen_func = convert_to_constants.convert_variables_to_constants_v2(concrete_func)

# Print the frozen graph's ops, to validate
for op in frozen_func.graph.get_operations():
    print(op.name)

# Save the frozen graph to a file
tf.io.write_graph(graph_or_graph_def=frozen_func.graph.as_graph_def(),
                  logdir="/content/gdrive/MyDrive/saved_model",
                  name="frozen_graph.pb",
                  as_text=False)



{'output_2': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, 'output_0': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, 'output_3': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, 'output_1': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>}
Input details:
Name: input, Shape: (1, 300, 300, 3), Type: <dtype: 'float32'>

Output details:
Name: output_2, Shape: (), Type: <dtype: 'float32'>
Name: output_0, Shape: (), Type: <dtype: 'float32'>
Name: output_3, Shape: (), Type: <dtype: 'float32'>
Name: output_1, Shape: (), Type: <dtype: 'float32'>
input
StatefulPartitionedCall/PartitionedCall/num_detections
unknown_150
unknown_173
unknown_168
unknown_176
unknown_256
unknown_151
unknown_170
unknown_165
unknown_285
unknown_294
unknown_154
unknown_159
unknown_205
unknown_166
unknown_184
unknown_179
unknown
unknown_157
unknown_19
unknown_212
unknown_174
unknown_187
unknown_182
unknown_275
unknown_286
unknown_158
unknown_213
unknown_221
unknown_228
unknown_244
unknown_183
unknown_193
unknown_276


'/content/gdrive/MyDrive/saved_model/frozen_graph.pb'

In [ ]:
import tensorflow as tf

# Load the model
model = tf.saved_model.load('/content/gdrive/MyDrive/saved_model')

# List all input information
concrete_func = model.signatures['serving_default']
print(concrete_func.inputs)


[<tf.Tensor 'input:0' shape=(1, 300, 300, 3) dtype=float32>, <tf.Tensor 'unknown:0' shape=() dtype=resource>, <tf.Tensor 'unknown_0:0' shape=() dtype=resource>, <tf.Tensor 'unknown_1:0' shape=() dtype=resource>, <tf.Tensor 'unknown_2:0' shape=() dtype=resource>, <tf.Tensor 'unknown_3:0' shape=() dtype=resource>, <tf.Tensor 'unknown_4:0' shape=() dtype=resource>, <tf.Tensor 'unknown_5:0' shape=() dtype=resource>, <tf.Tensor 'unknown_6:0' shape=() dtype=resource>, <tf.Tensor 'unknown_7:0' shape=() dtype=resource>, <tf.Tensor 'unknown_8:0' shape=() dtype=resource>, <tf.Tensor 'unknown_9:0' shape=() dtype=resource>, <tf.Tensor 'unknown_10:0' shape=() dtype=resource>, <tf.Tensor 'unknown_11:0' shape=() dtype=resource>, <tf.Tensor 'unknown_12:0' shape=() dtype=resource>, <tf.Tensor 'unknown_13:0' shape=() dtype=resource>, <tf.Tensor 'unknown_14:0' shape=() dtype=resource>, <tf.Tensor 'unknown_15:0' shape=() dtype=resource>, <tf.Tensor 'unknown_16:0' shape=() dtype=resource>, <tf.Tensor 'unkn

In [ ]:
import tensorflow as tf

# Load the frozen graph
graph_def = tf.compat.v1.GraphDef()
with tf.io.gfile.GFile('/content/gdrive/MyDrive/saved_model/frozen_graph.pb', 'rb') as f:
    graph_def.ParseFromString(f.read())

# Import the graph_def into a new Graph and returns it
with tf.Graph().as_default() as graph:
    tf.import_graph_def(graph_def, name='')

# Print the operation names to find the output node
for op in graph.get_operations():
    print(op.name)


input
StatefulPartitionedCall/PartitionedCall/num_detections
unknown_150
unknown_173
unknown_168
unknown_176
unknown_256
unknown_151
unknown_170
unknown_165
unknown_285
unknown_294
unknown_154
unknown_159
unknown_205
unknown_166
unknown_184
unknown_179
unknown
unknown_157
unknown_19
unknown_212
unknown_174
unknown_187
unknown_182
unknown_275
unknown_286
unknown_158
unknown_213
unknown_221
unknown_228
unknown_244
unknown_183
unknown_193
unknown_276
unknown_284
unknown_254
unknown_229
unknown_225
unknown_177
unknown_188
unknown_180
unknown_190
unknown_194
unknown_206
unknown_210
unknown_232
unknown_226
unknown_247
unknown_240
unknown_185
unknown_15
unknown_191
unknown_197
unknown_214
unknown_211
unknown_233
unknown_234
unknown_248
unknown_241
unknown_22
unknown_186
unknown_181
unknown_199
unknown_198
unknown_217
unknown_219
unknown_230
unknown_237
unknown_245
unknown_249
unknown_23
unknown_16
unknown_37
unknown_31
unknown_202
unknown_195
unknown_218
unknown_222
unknown_231
unknown_238
un

In [ ]:
import openvino as ov
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

!mo --input_model /content/gdrive/MyDrive/training/export_frozen_graph.pb \
--output_dir /content/gdrive/MyDrive/training/ \
--compress_to_fp16=True \
--reverse_input_channels \
--input_shape [1,300,300,3] \
--log_level DEBUG

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
2024-05-08 00:55:46.530154: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-08 00:55:46.615648: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-08 00:55:46.615946: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-08 00:55:46.616028: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-08 00:55:46.628754: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda driver

In [ ]:
'/content/gdrive/MyDrive/saved_model'

Eager execution: True
Frozen model has been saved.


In [ ]:
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

def load_and_freeze_model(saved_model_dir, output_graph_filename):
    # Load the TensorFlow SavedModel
    model = tf.saved_model.load(saved_model_dir)
    concrete_func = model.signatures['serving_default']

    # Concrete function already defines inputs and outputs, so use directly
    frozen_func = convert_variables_to_constants_v2(concrete_func)
    frozen_graph_def = frozen_func.graph.as_graph_def()

    # Print the layers of the frozen model
    layers = [op.name for op in frozen_func.graph.get_operations()]
    print("-" * 50)
    print("Frozen model layers: ")
    for layer in layers:
        print(layer)
    print("-" * 50)

    # Print the inputs and outputs of the frozen model
    print("Frozen model inputs: ", frozen_func.inputs)
    print("Frozen model outputs: ", frozen_func.outputs)

    # Save the frozen graph to a file
    tf.io.write_graph(frozen_graph_def, '.', output_graph_filename, as_text=False)
    print(f"Frozen model has been saved as {output_graph_filename}")

# Specify the SavedModel directory and output filename
saved_model_dir = '/content/gdrive/MyDrive/saved_model'
output_graph_filename = '/content/gdrive/MyDrive/saved_model/frozen_graph.pb'

# Call the function to load and freeze the model
load_and_freeze_model(saved_model_dir, output_graph_filename)


--------------------------------------------------
Frozen model layers: 
input
StatefulPartitionedCall/PartitionedCall/num_detections
unknown_107
unknown_205
unknown_123
unknown_221
unknown_228
unknown_244
unknown_27
unknown_30
unknown_49
unknown_47
unknown_56
unknown_62
unknown_79
unknown_76
unknown_94
unknown_93
unknown_109
unknown_108
unknown_116
unknown_120
unknown_139
unknown_135
unknown_148
unknown_2
unknown_6
unknown_28
unknown_29
unknown_52
unknown_48
unknown_64
unknown_63
unknown_82
unknown_84
unknown_97
unknown_90
unknown_112
unknown_105
unknown_124
unknown_121
unknown_142
unknown_136
unknown_9
unknown_25
unknown_53
unknown_45
unknown_67
unknown_60
unknown_83
unknown_87
unknown_98
unknown_91
unknown_113
unknown_106
unknown_127
unknown_129
unknown_143
unknown_144
unknown_46
unknown_68
unknown_61
unknown_80
unknown_3
unknown_95
unknown_99
unknown_110
unknown_114
unknown_128
unknown_132
unknown_140
unknown_147
unknown_145
unknown_54
unknown_65
unknown_69
unknown_81
unknown_96
un

In [ ]:
!ovc /content/gdrive/MyDrive/saved_model/frozen_graph.pb \
--output_model  /content/gdrive/MyDrive//saved_model/ \
--compress_to_fp16=False

[ SUCCESS ] XML file: /content/gdrive/MyDrive//saved_model/frozen_graph.xml
[ SUCCESS ] BIN file: /content/gdrive/MyDrive//saved_model/frozen_graph.bin


In [ ]:
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

model = tf.saved_model.load('/content/gdrive/MyDrive/custom_model_lite/saved_model/')
frozen_func = convert_variables_to_constants_v2(model.signatures['serving_default'], lower_control_flow=False)
graph_def = frozen_func.graph.as_graph_def(add_shapes=True)
tf.io.write_graph(graph_def, '/content/gdrive/MyDrive/custom_model_lite/saved_model/frozen/', 'frozen_model.pb', as_text=False)


'/content/gdrive/MyDrive/custom_model_lite/saved_model/frozen/frozen_model.pb'